import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BlurryBlob from "@/components/animata/background/blurry-blob";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Blurry Blob Background */}
        <BlurryBlob 
          firstBlobColor="bg-blue-600" 
          secondBlobColor="bg-purple-600"
        />
        {/* Content wrapper */}
        <div className="relative z-0">
          {children}
        </div>
      </body>
    </html>
  );
}
